import type {
  AnalyticsFact,
  CandidateRow,
  PlayerSession,
} from "@/lib/api/types";

export const fact: AnalyticsFact = {
  kind: "latest_comparison",
  status: "ok",
  rule_version: "analytics_v1",
  metric_key: "total_distance_m",
  value: "8400",
  display_value: "8400",
  unit: "m",
  baseline_value: "7500",
  delta: "900",
  percent_change: "12",
  slope_per_week: null,
  median_value: null,
  mad: null,
  score: null,
  sample_size: 5,
  session_ids: ["s1", "s2"],
  source_observation_ids: ["o1", "o2"],
  points: [],
  supporting_metrics: [],
  from_date: "2026-01-01",
  to_date: "2026-02-01",
  definition_id: "metrics_v1",
  comparability_key: "metrics_v1:total_distance_m",
  note: null,
};
export const playerSession: PlayerSession = {
  id: "s1",
  player_id: "p1",
  local_date: "2026-02-01",
  session_type: "training",
  quality_state: "accepted",
  metrics: [
    {
      metric_key: "total_distance_m",
      value: "8400",
      unit: "m",
      source_label: "Distance (m)",
      definition_id: "metrics_v1",
      comparability_key: "metrics_v1:total_distance_m",
      quality_state: "accepted",
    },
    {
      metric_key: "maximum_velocity_kmh",
      value: "31.2",
      unit: "km/h",
      source_label: "Maximum Velocity",
      definition_id: "metrics_v1",
      comparability_key: "metrics_v1:maximum_velocity_kmh",
      quality_state: "accepted",
    },
  ],
  warnings: [],
  provenance: { source_athlete_row_id: "r1", report_upload_id: "u1" },
};
export const row: CandidateRow = {
  id: "r1",
  row_ordinal: 3,
  source_name: "Synthetic Athlete C",
  source_position_code: "MID",
  quality_state: "ready",
  metrics: [
    {
      source_label: "Distance (m)",
      raw_value: "8400",
      raw_unit: "m",
      parsed_value: "8400",
      quality_state: "accepted",
      source_locator: "page:1/table:3",
    },
  ],
  missing_metrics: ["Maximum Velocity"],
  findings: [],
  links: [],
};
